[project]
name = "biocomp"
version = "25.12"
description = "BioComp Streamlit web application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chemics>=24.1",
    "streamlit>=1.52.1",
    "streamlit-bokeh>=3.8.0",
]

[tool.ruff]
line-length = 100
